apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "processor.fullname" . }}
  labels:
    {{- include "processor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "processor.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "processor.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: processor
        image: "{{ .Values.image.name }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}

        envFrom:
        {{- if .Values.configmap.enabled }}
        - configMapRef:
            name: {{ include "processor.fullname" . }}
        {{- end }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        livenessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}

        readinessProbe:
          httpGet:
            path: {{ .Values.probes.path }}
            port: {{ .Values.service.port }}
          initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.periodSeconds }}