name: Ingress Deploy

on:
  workflow_dispatch:

jobs:
  Ingress-Deploy:
    name: Deploy Ingress
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
        working-directory: Helm-Charts

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Current Path
        run: |
          pwd
          ls -lrt

      - name: Verify Cluster Access
        run: kubectl get nodes

      - name: Deploy Ingress
        run: kubectl apply -f ingress.yaml