name: Service Mesh Deploy
on:
  workflow_dispatch:

jobs:
  Install-Istio-Dev:
    name: 'Istio Deployment'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: istio-1.20.2

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Istio
      run: |
          cd Istio-Artifacts
          export PATH=$PWD/bin:$PATH
          chmod +x bin/istioctl
          istioctl install --set profile="default" -y
          kubectl label namespace default istio-injection=enabled
    
    - name: Install prometheus
      run: |
         kubectl apply -f Istio-Artifacts/prometheus.yaml

    - name: Install Grafana
      run: |
         kubectl apply -f Istio-Artifacts/grafana.yaml

    - name: Install Kiali
      run: |
         kubectl apply -f Istio-Artifacts/kiali.yaml