name: Service Mesh Deploy

on:
  workflow_dispatch:

jobs:

  Install-Istio-Dev:
    name: Istio Deployment
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Istio
        run: |
          curl -L https://istio.io/downloadIstio | sh -

      - name: Install Istio
        run: |
          cd istio-*
          export PATH=$PWD/bin:$PATH
          istioctl version
          istioctl install --set profile=default -y
          kubectl label namespace payment istio-injection=enabled --overwrite

      - name: Install Prometheus
        run: |
          kubectl apply -f Helm-Charts/prometheus.yaml

      - name: Install Grafana
        run: |
          kubectl apply -f Helm-Charts/grafana.yaml
